package com.redmechax00.cbrvaluterate.recyclerview

import android.annotation.SuppressLint
import com.redmechax00.cbrvaluterate.R
import com.redmechax00.cbrvaluterate.models.ValuteModel
import com.redmechax00.cbrvaluterate.utilits.APP_ACTIVITY

object ValuteObject {

    var countId: Int = 0

    @SuppressLint("UseCompatLoadingForDrawables")
    fun getUsers() = arrayListOf(
        ValuteModel(
            getUid(),
            APP_ACTIVITY.getString(R.string.valute_char_code_aud),
            APP_ACTIVITY.getString(R.string.valute_name_aud),
            APP_ACTIVITY.getDrawable(R.drawable.ic_australia)
        ),
        ValuteModel(
            getUid(),
            APP_ACTIVITY.getString(R.string.valute_char_code_azn),
            APP_ACTIVITY.getString(R.string.valute_name_azn),
            APP_ACTIVITY.getDrawable(R.drawable.ic_azerbaijan)

        ),
        ValuteModel(
            getUid(),
            APP_ACTIVITY.getString(R.string.valute_char_code_gbp),
            APP_ACTIVITY.getString(R.string.valute_name_gbp),
            APP_ACTIVITY.getDrawable(R.drawable.ic_great_britain)

        ),
        ValuteModel(
            getUid(),
            APP_ACTIVITY.getString(R.string.valute_char_code_amd),
            APP_ACTIVITY.getString(R.string.valute_name_amd),
            APP_ACTIVITY.getDrawable(R.drawable.ic_armenia)

        ),
        ValuteModel(
            getUid(),
            APP_ACTIVITY.getString(R.string.valute_char_code_byn),
            APP_ACTIVITY.getString(R.string.valute_name_byn),
            APP_ACTIVITY.getDrawable(R.drawable.ic_belarus)
        ),
        ValuteModel(
            getUid(),
            APP_ACTIVITY.getString(R.string.valute_char_code_bgn),
            APP_ACTIVITY.getString(R.string.valute_name_bgn),
            APP_ACTIVITY.getDrawable(R.drawable.ic_bulgaria)
        ),
        ValuteModel(
            getUid(),
            APP_ACTIVITY.getString(R.string.valute_char_code_brl),
            APP_ACTIVITY.getString(R.string.valute_name_brl),
            APP_ACTIVITY.getDrawable(R.drawable.ic_brazil)
        ),
        ValuteModel(
            getUid(),
            APP_ACTIVITY.getString(R.string.valute_char_code_huf),
            APP_ACTIVITY.getString(R.string.valute_name_huf),
            APP_ACTIVITY.getDrawable(R.drawable.ic_hungary)
        ),
        ValuteModel(
            getUid(),
            APP_ACTIVITY.getString(R.string.valute_char_code_hkd),
            APP_ACTIVITY.getString(R.string.valute_name_hkd),
            APP_ACTIVITY.getDrawable(R.drawable.ic_hongkong)
        ),
        ValuteModel(
            getUid(),
            APP_ACTIVITY.getString(R.string.valute_char_code_dkk),
            APP_ACTIVITY.getString(R.string.valute_name_dkk),
            APP_ACTIVITY.getDrawable(R.drawable.ic_denmark)
        ),
        ValuteModel(
            getUid(),
            APP_ACTIVITY.getString(R.string.valute_char_code_usd),
            APP_ACTIVITY.getString(R.string.valute_name_usd),
            APP_ACTIVITY.getDrawable(R.drawable.ic_usa)
        ),
        ValuteModel(
            getUid(),
            APP_ACTIVITY.getString(R.string.valute_char_code_eur),
            APP_ACTIVITY.getString(R.string.valute_name_eur),
            APP_ACTIVITY.getDrawable(R.drawable.ic_europe)
        ),
        ValuteModel(
            getUid(),
            APP_ACTIVITY.getString(R.string.valute_char_code_inr),
            APP_ACTIVITY.getString(R.string.valute_name_inr),
            APP_ACTIVITY.getDrawable(R.drawable.ic_india)
        ),
        ValuteModel(
            getUid(),
            APP_ACTIVITY.getString(R.string.valute_char_code_kzt),
            APP_ACTIVITY.getString(R.string.valute_name_kzt),
            APP_ACTIVITY.getDrawable(R.drawable.ic_kazakhstan)
        ),
        ValuteModel(
            getUid(),
            APP_ACTIVITY.getString(R.string.valute_char_code_kgs),
            APP_ACTIVITY.getString(R.string.valute_name_kgs),
            APP_ACTIVITY.getDrawable(R.drawable.ic_kyrgyzstan)
        ),
        ValuteModel(
            getUid(),
            APP_ACTIVITY.getString(R.string.valute_char_code_cny),
            APP_ACTIVITY.getString(R.string.valute_name_cny),
            APP_ACTIVITY.getDrawable(R.drawable.ic_china)
        ),
        ValuteModel(
            getUid(),
            APP_ACTIVITY.getString(R.string.valute_char_code_mdl),
            APP_ACTIVITY.getString(R.string.valute_name_mdl),
            APP_ACTIVITY.getDrawable(R.drawable.ic_moldova_circular)
        ),
        ValuteModel(
            getUid(),
            APP_ACTIVITY.getString(R.string.valute_char_code_nok),
            APP_ACTIVITY.getString(R.string.valute_name_nok),
            APP_ACTIVITY.getDrawable(R.drawable.ic_norway)
        ),
        ValuteModel(
            getUid(),
            APP_ACTIVITY.getString(R.string.valute_char_code_pln),
            APP_ACTIVITY.getString(R.string.valute_name_pln),
            APP_ACTIVITY.getDrawable(R.drawable.ic_poland)
        ),
        ValuteModel(
            getUid(),
            APP_ACTIVITY.getString(R.string.valute_char_code_ron),
            APP_ACTIVITY.getString(R.string.valute_name_ron),
            APP_ACTIVITY.getDrawable(R.drawable.ic_romania)
        ),
        ValuteModel(
            getUid(),
            APP_ACTIVITY.getString(R.string.valute_char_code_xdr),
            APP_ACTIVITY.getString(R.string.valute_name_xdr),
            APP_ACTIVITY.getDrawable(androidx.core.R.drawable.notification_icon_background)
        ),
        ValuteModel(
            getUid(),
            APP_ACTIVITY.getString(R.string.valute_char_code_sgd),
            APP_ACTIVITY.getString(R.string.valute_name_sgd),
            APP_ACTIVITY.getDrawable(R.drawable.ic_singapore)
        ),
        ValuteModel(
            getUid(),
            APP_ACTIVITY.getString(R.string.valute_char_code_tjs),
            APP_ACTIVITY.getString(R.string.valute_name_tjs),
            APP_ACTIVITY.getDrawable(R.drawable.ic_tajikistan)
        ),
        ValuteModel(
            getUid(),
            APP_ACTIVITY.getString(R.string.valute_char_code_try),
            APP_ACTIVITY.getString(R.string.valute_name_try),
            APP_ACTIVITY.getDrawable(R.drawable.ic_turkey)
        ),
        ValuteModel(
            getUid(),
            APP_ACTIVITY.getString(R.string.valute_char_code_tmt),
            APP_ACTIVITY.getString(R.string.valute_name_tmt),
            APP_ACTIVITY.getDrawable(R.drawable.ic_turkmenistan_circular)
        ),
        ValuteModel(
            getUid(),
            APP_ACTIVITY.getString(R.string.valute_char_code_uzs),
            APP_ACTIVITY.getString(R.string.valute_name_uzs),
            APP_ACTIVITY.getDrawable(R.drawable.ic_uzbekistan)
        ),
        ValuteModel(
            getUid(),
            APP_ACTIVITY.getString(R.string.valute_char_code_czk),
            APP_ACTIVITY.getString(R.string.valute_name_czk),
            APP_ACTIVITY.getDrawable(R.drawable.ic_czech_republic)
        ),
        ValuteModel(
            getUid(),
            APP_ACTIVITY.getString(R.string.valute_char_code_sek),
            APP_ACTIVITY.getString(R.string.valute_name_sek),
            APP_ACTIVITY.getDrawable(R.drawable.ic_sweden)
        ),
        ValuteModel(
            getUid(),
            APP_ACTIVITY.getString(R.string.valute_char_code_chf),
            APP_ACTIVITY.getString(R.string.valute_name_chf),
            APP_ACTIVITY.getDrawable(R.drawable.ic_switzerland)
        ),
        ValuteModel(
            getUid(),
            APP_ACTIVITY.getString(R.string.valute_char_code_zar),
            APP_ACTIVITY.getString(R.string.valute_name_zar),
            APP_ACTIVITY.getDrawable(R.drawable.ic_south_africa)
        ),
        ValuteModel(
            getUid(),
            APP_ACTIVITY.getString(R.string.valute_char_code_krw),
            APP_ACTIVITY.getString(R.string.valute_name_krw),
            APP_ACTIVITY.getDrawable(R.drawable.ic_south_korea)
        ),
        ValuteModel(
            getUid(),
            APP_ACTIVITY.getString(R.string.valute_char_code_jpy),
            APP_ACTIVITY.getString(R.string.valute_name_jpy),
            APP_ACTIVITY.getDrawable(R.drawable.ic_japan)
        )
    )

    private fun getUid(): Int = countId++

}